name: "build"
on:
  push:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-22.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: cargo build
        run: cargo build
      - name: cargo test
        run: cargo test
      # - name: cargo tarpaulin
      #   run: cargo tarpaulin
